spring.application.name=lunchpad


#DB config

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/launchpadDB
spring.datasource.username=postgres
spring.datasource.password=123

#hibernate config

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Jwt-Secret-key

jwt.secret=a1b2c3d4e5g6h7ibrgbihjdfighbdutbgdiogodfbg123gff769rgf2002
jwt.expiration=3600000